// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcThOKp7lYqlmXBgJlRMNhRoqmtTSS21A',
    appId: '1:829972933157:web:67653e4426876368352dcc',
    messagingSenderId: '829972933157',
    projectId: 'dalel-4a3a9',
    authDomain: 'dalel-4a3a9.firebaseapp.com',
    storageBucket: 'dalel-4a3a9.firebasestorage.app',
    measurementId: 'G-WXSBC532QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfTFzJ8rb2JRldBXaoA3_ZhFQux_EhxdY',
    appId: '1:829972933157:android:5629d1f6a9520e6f352dcc',
    messagingSenderId: '829972933157',
    projectId: 'dalel-4a3a9',
    storageBucket: 'dalel-4a3a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzVX0PpQV5Mw-bawYKjX0BlqYx0bHGfcE',
    appId: '1:829972933157:ios:0ef583ec02997b1c352dcc',
    messagingSenderId: '829972933157',
    projectId: 'dalel-4a3a9',
    storageBucket: 'dalel-4a3a9.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzVX0PpQV5Mw-bawYKjX0BlqYx0bHGfcE',
    appId: '1:829972933157:ios:0ef583ec02997b1c352dcc',
    messagingSenderId: '829972933157',
    projectId: 'dalel-4a3a9',
    storageBucket: 'dalel-4a3a9.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcThOKp7lYqlmXBgJlRMNhRoqmtTSS21A',
    appId: '1:829972933157:web:9ba1035b8baadf85352dcc',
    messagingSenderId: '829972933157',
    projectId: 'dalel-4a3a9',
    authDomain: 'dalel-4a3a9.firebaseapp.com',
    storageBucket: 'dalel-4a3a9.firebasestorage.app',
    measurementId: 'G-HHJRS1E52J',
  );
}
